FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install --save-dev @testing-library/react @testing-library/jest-dom @testing-library/user-event vitest jsdom

COPY . .

EXPOSE 3000

ENV HOST=0.0.0.0

CMD ["npm", "start"]